# Use nvidia/cuda as the base image
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

# Set environment variables for Miniconda
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"

# Update and install wget and libpq-dev
RUN apt-get update && \
    apt-get install -y wget libpq-dev && \
    apt-get install -y libgl1-mesa-glx && \
    apt-get install -y libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

# Install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py39_23.1.0-1-Linux-x86_64.sh && \
    bash Miniconda3-py39_23.1.0-1-Linux-x86_64.sh -b -p /root/miniconda3 && \
    rm -f Miniconda3-py39_23.1.0-1-Linux-x86_64.sh && \
    conda --version

# Ensure conda base environment activation on each new shell
RUN echo "source activate base" >> ~/.bashrc

# install main packages
COPY ./scripts/setup /tmp/prep/scripts/setup

RUN chmod +x /tmp/prep/scripts/setup/major.sh && /tmp/prep/scripts/setup/major.sh
RUN chmod +x /tmp/prep/scripts/setup/minor.sh && /tmp/prep/scripts/setup/minor.sh

# Set the working directory to /aiv (assuming your app resides there)
WORKDIR /aiv